plugins {
    id 'com.android.application'
}

android {
    namespace 'com.tbilx98.notificationbadge'
    compileSdk 35

    defaultConfig {
        applicationId 'com.tbilx98.notificationbadge'
        minSdk 28
        targetSdk 28
        versionCode 2
        versionName '2.0'
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
